  paths: 
    /api/productos: 
      get: 
        summary: Obtener productos
        tags:
        - productos
        description: Esta ruta se utiliza para obtener la lista de productos.
        security: 
            - BearerAuth: []
        responses: 
          200: 
            description: OK
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/ProductosResponse'
          500: 
            description: Internal Server Error,
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
          401: 
            description: Unauthorized
      post: 
        summary: Crear un producto
        tags:
        - productos
        description: Esta ruta se utiliza para crear un nuevo producto.
        security: 
            - BearerAuth: []
        requestBody: 
          required: true,
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Producto'
        responses: 
          201: 
            description: Created
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Producto'
          500: 
            description: Internal Server Error
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
    /api/productos/{id}: 
      get: 
        summary: Obtener un producto por su ID
        tags:
        - productos
        description: Esta ruta se utiliza para obtener un producto específico por su ID.
        security: 
            - BearerAuth: []
        parameters: 
          - name: id
            in: path
            description: ID del producto
            required: true
            schema: 
              type: string
        responses: 
          200: 
            description: OK
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Producto'
          500: 
            description: Internal Server Error
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
          401: 
            description: Unauthorized
          404": 
            description: Not Found
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
      put: 
        summary: Actualizar un producto por su ID
        tags:
        - productos
        description: Esta ruta se utiliza para actualizar un producto específico por su ID.
        security: 
            - BearerAuth: []
        parameters: 
          - name: id,
            in: path,
            description: ID del producto
            required: true
            schema: 
              type: string
        requestBody: 
          required: true
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/Producto'
        responses: 
          200: 
            description: OK
            content: 
              application/json: 
                schema: 
                  type: object
                  properties: 
                    message: 
                      type: string
          500: 
            description: Internal Server Error
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
          401: 
            description: Unauthorized
          404: 
            description: Not Found
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
      delete: 
        summary: Eliminar un producto por su ID
        tags:
        - productos
        description: Esta ruta se utiliza para eliminar un producto específico por su ID.
        security: 
            - BearerAuth: []
        parameters: 
          - name: id
            in: path
            description: ID del producto
            required: true
            schema: 
              type: string
        responses: 
          200: 
            description: OK
            content: 
              application/json: 
                schema: 
                  type: object
                  properties: 
                    message: 
                      type: string
          500: 
            description: Internal Server Error
            content: 
              application/json: 
                schema: 
                  $ref: '#/components/schemas/Error'
          401: 
            description: Unauthorized
          404: 
            description: Not Found
            content: 
              application/json: 
                schema:
                  $ref: '#/components/schemas/Error' 
  components: 
    schemas: 
      ProductosResponse: 
        type: object
        properties: 
          productos: 
            type: array
            items: 
              $ref: '#/components/schemas/Producto'
      Producto: 
        type: object
        properties: 
          id: 
            type: string
          title: 
            type: string
          description: 
            type: string
          price: 
            type: number
          thumbnail: 
            type: string
          code:
            type: string
          stock: 
            type: number
          category: 
            type: string
          password: 
            type: string
      Error: 
        type: object
        properties: 
          name: 
            type: string
          cause: 
            type: string
          message: 
            type: string
          code: 
            type: integer